version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Instalando dependências..."
      - yarn install --prod
  build:
    commands:
      - echo "Fazendo build do projeto..."
      - yarn run build
artifacts:
  base-directory: build
  files:
    - '**/*'
