version: 0.0
os: linux
files:
  - source: /backend
    destination: /usr/share/nginx/html
permissions:
  - object: /usr/share/nginx/html
    owner: nginx
    group: nginx
hooks:
  AfterInstall:
    - location: scripts/install-prod.sh
      runas: nginx
