version: 0.0
os: linux
files:
  - source: /backend
    destination: /usr/share/nginx/html
permissions:
  - object: /usr/share/nginx/html
    owner: nginx
    group: nginx
hooks:
  BeforeInstall:
    - location: scripts/env-vars-inject.sh
      timeout: 300
  AfterInstall:
    - location: scripts/install-prod.sh
      runas: nginx
      timeout: 300
