version: '3.7'
services:
  frontend:
    build:
      context: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontendModules:/app/node_modules
    environment:
      REACT_APP_API_URL: http://localhost:8000
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backendLogs:/app/logs
      - backendVendor:/app/vendor
    environment:
      docker: "true"

  db:
    image: mariadb:10.9
    volumes:
      - dbVolume:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MARIADB_DATABASE: app
      MARIADB_ROOT_PASSWORD: root

volumes:
  backendLogs:
    driver: local
  backendVendor:
    driver: local
  frontendModules:
    driver: local
  dbVolume:
    driver: local
