version: 0.2
phases:
  install:
    commands:
      - cd backend
      - echo "Instalando dependências de teste..."
      - composer install --dev
  pre_build:
    commands:
      - echo "Rodando testes..."
      - composer test --no-interaction
  build:
    commands:
      - echo "Instalando dependências de produção..."
      - composer install --no-dev
artifacts:
  files:
    - 'backend/app/*'
    - 'backend/public/*'
    - 'backend/src/*'
    - 'backend/vendor/*'
    - 'backend/composer.json'
    - 'backend/composer.lock'
    - 'appspec.yml'
    - 'scripts/install-prod.sh'
cache:
  paths:
    - 'backend/vendor'
