version: 0.2
phases:
  install:
    commands:
      - cd backend
      - echo "Instalando dependências..."
      - composer install --no-dev
  pre_build:
    commands:
      - echo "Rodando testes..."
      - composer test --no-interaction
artifacts:
  files:
    - 'backend/app/*'
    - 'backend/public/*'
    - 'backend/src/*'
    - 'backend/vendor/*'
    - 'backend/composer.json'
    - 'backend/composer.lock'
    - 'appspec.yml'
cache:
  paths:
    - 'backend/vendor'
